language: cpp
os: linux
dist: jammy

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake python3 python3-pip
  - git clone https://github.com/catchorg/Catch2.git
  - cd Catch2
  - cmake -Bbuild -H. -DBUILD_TESTING=OFF
  - sudo cmake --build build/ -j $(nproc) --target install
  - cd ..
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake .. -Dcoverage=ON -DCMAKE_BUILD_TYPE=Debug
  - make
  - ctest --output-on-failure
  - cd ..

after_success:
  - coveralls -r . -b build/ -i varvec.hpp --gcov-options '\-lp'
