language: cpp
os: linux
dist: jammy

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y clang-14 cmake libc++-14-dev libc++abi-14-dev
  - git clone https://github.com/catchorg/Catch2.git
  - cd Catch2
  - CC=/usr/bin/clang-14 CXX="/usr/bin/clang++-14 -stdlib=libc++" cmake -Bbuild -H. -DBUILD_TESTING=OFF
  - sudo cmake --build build/ --target install
  - cd ..

script:
  - mkdir build
  - cd build
  - CC=/usr/bin/clang-14 CXX=/usr/bin/clang++-14 cmake ..
  - make
  - ctest --verbose
